# This config file is used by ros2_control
/**/controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # arm_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


/**/left_arm_controller:
  ros__parameters:
    joints:
      - joint1_left
      - joint2_left
      - joint3_left
      - joint4_left
      - joint5_left
      - joint6_left
      - joint7_left
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

/**/right_arm_controller:
  ros__parameters:
    joints:
      - joint1_right
      - joint2_right
      - joint3_right
      - joint4_right
      - joint5_right
      - joint6_right
      - joint7_right
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
